// ==========================================
        // EXERCISE DATABASE - Carga perezosa (lazy loading)
        // ==========================================
        let exerciseDatabase = null;

        function getExerciseDatabase() {
            if (exerciseDatabase) return exerciseDatabase;
            exerciseDatabase = [
                // LUNES (sin cambios)
                {
                    id: 'press-plano',
                    nombre: 'Press plano con mancuernas',
                    grupo: 'Pecho',
                    categoria: 'Press',
                    urlGif: 'https://gymvisual.com/img/p/1/8/6/4/5/18645.gif',
                    descripcion: 'Tumbado sobre un banco plano, baja las mancuernas de forma controlada hasta el pecho y empuja hacia arriba manteniendo siempre el control del movimiento.',
                    consejos: '• Baja lentamente (2-3 segundos).\n• Mantén las muñecas rectas.\n• Exhala al empujar.',
                    errores: '• No bajes demasiado rápido.\n• No bloquees los codos.\n• No pierdas el control.',
                    musculosPrincipales: ['Pectoral mayor', 'Tríceps', 'Deltoides anterior'],
                    musculosSecundarios: ['Serrato anterior'],
                    series: 4,
                    reps: '8-12',
                    descanso: 90,
                    dia: 'lunes',
                    dificultad: 'media',
                    material: ['Banco', 'Mancuernas'],
                    intensidadMuscular: { 'Pecho': 90, 'Tríceps': 75, 'Hombro': 65 }
                },
                {
                    id: 'press-inclinado',
                    nombre: 'Press inclinado con mancuernas',
                    grupo: 'Pecho',
                    categoria: 'Press',
                    urlGif: 'https://fitnessprogramer.com/wp-content/uploads/2022/07/Dumbbell-Reverse-Grip-30-Degrees-Incline-Bench-Press.gif',
                    descripcion: 'Con el banco inclinado entre 30° y 45°, baja las mancuernas lentamente hasta el pecho y vuelve a empujarlas hacia arriba trabajando la parte superior del pectoral.',
                    consejos: '• El banco debe estar entre 30° y 45°.\n• Mantén las muñecas rectas.\n• Exhala al empujar.',
                    errores: '• No uses un ángulo demasiado vertical.\n• No bajes más allá del pecho.',
                    musculosPrincipales: ['Pectoral superior', 'Deltoides anterior', 'Tríceps'],
                    musculosSecundarios: ['Serrato anterior', 'Trapecio'],
                    series: 4,
                    reps: '8-12',
                    descanso: 90,
                    dia: 'lunes',
                    dificultad: 'media',
                    material: ['Banco inclinado', 'Mancuernas'],
                    intensidadMuscular: { 'Pecho': 85, 'Hombro': 70, 'Tríceps': 70 }
                },
                {
                    id: 'aperturas',
                    nombre: 'Aperturas con mancuernas',
                    grupo: 'Pecho',
                    categoria: 'Apertura',
                    urlGif: 'https://gymvisual.com/img/p/1/0/2/8/0/10280.gif',
                    descripcion: 'Tumbado en banco plano, abre los brazos manteniendo una ligera flexión de los codos hasta notar el estiramiento del pecho, y vuelve lentamente.',
                    consejos: '• Mantén los codos ligeramente flexionados.\n• Siente el estiramiento.\n• Controla el movimiento.',
                    errores: '• No bloquees los codos.\n• No uses demasiado peso.',
                    musculosPrincipales: ['Pectoral mayor', 'Deltoides anterior'],
                    musculosSecundarios: ['Bíceps', 'Serrato anterior'],
                    series: 4,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'lunes',
                    dificultad: 'facil',
                    material: ['Banco', 'Mancuernas'],
                    intensidadMuscular: { 'Pecho': 80, 'Hombro': 50 }
                },
                {
                    id: 'press-militar',
                    nombre: 'Press militar sentado',
                    grupo: 'Hombro',
                    categoria: 'Press',
                    urlGif: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif',
                    descripcion: 'Sentado en el banco con la espalda apoyada, empuja las mancuernas por encima de la cabeza y baja lentamente hasta la altura de los hombros.',
                    consejos: '• Mantén la espalda apoyada.\n• No arquees la zona lumbar.\n• Controla la bajada.',
                    errores: '• No bloquees los codos.\n• No inclines el cuerpo.',
                    musculosPrincipales: ['Deltoides', 'Tríceps', 'Trapecio'],
                    musculosSecundarios: ['Serrato anterior'],
                    series: 4,
                    reps: '8-12',
                    descanso: 90,
                    dia: 'lunes',
                    dificultad: 'media',
                    material: ['Banco', 'Mancuernas'],
                    intensidadMuscular: { 'Hombro': 90, 'Tríceps': 70, 'Trapecio': 60 }
                },
                {
                    id: 'elevaciones-laterales',
                    nombre: 'Elevaciones laterales',
                    grupo: 'Hombro',
                    categoria: 'Aislamiento',
                    urlGif: 'https://gymvisual.com/img/p/5/1/3/7/5137.gif',
                    descripcion: 'De pie o sentado, eleva las mancuernas lateralmente hasta la altura de los hombros manteniendo una ligera flexión en los codos.',
                    consejos: '• Mantén los codos ligeramente flexionados.\n• No uses demasiado peso.\n• Controla el movimiento.',
                    errores: '• No balancees el cuerpo.\n• No uses impulso.',
                    musculosPrincipales: ['Deltoides medio', 'Supraespinoso'],
                    musculosSecundarios: ['Trapecio'],
                    series: 4,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'lunes',
                    dificultad: 'facil',
                    material: ['Mancuernas'],
                    intensidadMuscular: { 'Hombro': 85 }
                },
                {
                    id: 'elevaciones-frontales',
                    nombre: 'Elevaciones frontales',
                    grupo: 'Hombro',
                    categoria: 'Aislamiento',
                    urlGif: 'https://gymvisual.com/img/p/2/4/9/4/0/24940.gif',
                    descripcion: 'De pie, eleva las mancuernas hacia delante hasta la altura de los hombros sin balancear el cuerpo.',
                    consejos: '• Mantén los brazos extendidos.\n• Controla la subida y la bajada.',
                    errores: '• No balancees el cuerpo.\n• No uses demasiado peso.',
                    musculosPrincipales: ['Deltoides anterior'],
                    musculosSecundarios: ['Pectoral'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'miercoles',
                    dificultad: 'facil',
                    material: ['Mancuernas'],
                    intensidadMuscular: { 'Hombro': 75 }
                },
                {
                    id: 'extension-triceps-cabeza',
                    nombre: 'Extensión de tríceps por encima de la cabeza',
                    grupo: 'Tríceps',
                    categoria: 'Aislamiento',
                    urlGif: 'https://media.tenor.com/V3J-mg9gH0kAAAAM/seated-dumbbell-triceps-extension.gif',
                    descripcion: 'Sentado, sujeta una mancuerna con ambas manos por encima de la cabeza y extiende completamente los brazos manteniendo los codos cerca de la cabeza.',
                    consejos: '• Mantén los codos cerca de la cabeza.\n• Controla el movimiento.',
                    errores: '• No separes los codos.\n• No bajes demasiado rápido.',
                    musculosPrincipales: ['Tríceps (cabeza larga)'],
                    musculosSecundarios: ['Tríceps (cabeza lateral)', 'Tríceps (cabeza medial)'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'miercoles',
                    dificultad: 'facil',
                    material: ['Mancuerna'],
                    intensidadMuscular: { 'Tríceps': 90 }
                },
                {
                    id: 'press-cerrado',
                    nombre: 'Press cerrado con mancuernas',
                    grupo: 'Tríceps',
                    categoria: 'Press',
                    urlGif: 'https://gymvisual.com/img/p/7/5/3/5/7535.gif',
                    descripcion: 'Tumbado en banco plano, mantén las mancuernas juntas durante todo el recorrido, con las palmas enfrentadas.',
                    consejos: '• Mantén las mancuernas juntas.\n• Controla el movimiento.',
                    errores: '• No separes las mancuernas.\n• No bloquees los codos.',
                    musculosPrincipales: ['Tríceps'],
                    musculosSecundarios: ['Pectoral'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'miercoles',
                    dificultad: 'media',
                    material: ['Banco', 'Mancuernas'],
                    intensidadMuscular: { 'Tríceps': 85, 'Pecho': 50 }
                },

                // MARTES (sin cambios)
                {
                    id: 'barbell-row',
                    nombre: 'Barbell Row',
                    grupo: 'Espalda',
                    categoria: 'Remo',
                    urlGif: 'https://mundoentrenamiento.com/wp-content/uploads/2019/10/Remo-con-barra-agarre-cerrado.gif',
                    descripcion: 'De pie, con una barra sujeta con las manos y las rodillas ligeramente flexionadas, inclina el torso hacia delante manteniendo la espalda recta. Lleva la barra hacia la parte baja del abdomen, acercando los codos al cuerpo. Aprieta la espalda al llegar arriba y baja la barra de forma controlada. Evita redondear la espalda o utilizar impulso.',
                    consejos: '• Mantén la espalda recta en todo momento.\n• Lleva los codos hacia atrás y cerca del cuerpo.\n• Aprieta los omóplatos al final del movimiento.\n• Baja la barra de forma controlada.',
                    errores: '• No redondees la espalda.\n• No uses impulso para levantar el peso.\n• No tires con los brazos sin activar la espalda.',
                    musculosPrincipales: ['Dorsal ancho', 'Espalda media', 'Romboides'],
                    musculosSecundarios: ['Bíceps', 'Trapecio medio'],
                    series: 4,
                    reps: '8-12',
                    descanso: 90,
                    dia: 'martes',
                    dificultad: 'media',
                    material: ['Barra', 'Discos'],
                    intensidadMuscular: { 'Espalda': 90, 'Bíceps': 60 }
                },
                {
                    id: 'one-arm-dumbbell-row',
                    nombre: 'One-Arm Dumbbell Row',
                    grupo: 'Espalda',
                    categoria: 'Remo',
                    urlGif: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Row.gif',
                    descripcion: 'Apoya una mano y una rodilla sobre un banco y coloca el otro pie firmemente en el suelo. Sujeta una mancuerna con la mano libre y deja el brazo extendido hacia abajo. Tira de la mancuerna hacia la cadera llevando el codo hacia atrás, manteniendo el torso estable. Baja lentamente hasta extender de nuevo el brazo. Evita girar el cuerpo para levantar más peso.',
                    consejos: '• Mantén el torso estable y la espalda recta.\n• Lleva el codo hacia atrás y cerca del cuerpo.\n• Siente la contracción de la espalda al subir.\n• Baja la mancuerna de forma controlada.',
                    errores: '• No gires el cuerpo para levantar más peso.\n• No redondees la espalda.\n• No uses impulso.',
                    musculosPrincipales: ['Dorsal ancho', 'Espalda media'],
                    musculosSecundarios: ['Bíceps', 'Romboides'],
                    series: 4,
                    reps: '8-12',
                    descanso: 90,
                    dia: 'martes',
                    dificultad: 'media',
                    material: ['Banco', 'Mancuerna'],
                    intensidadMuscular: { 'Espalda': 85, 'Bíceps': 55 }
                },
                {
                    id: 'dumbbell-reverse-fly',
                    nombre: 'Dumbbell Reverse Fly',
                    grupo: 'Espalda',
                    categoria: 'Aislamiento',
                    urlGif: 'https://gymvisual.com/img/p/5/1/2/4/5124.gif',
                    descripcion: 'Inclínate hacia delante manteniendo la espalda recta y sujeta una mancuerna en cada mano con los brazos ligeramente flexionados. Abre los brazos hacia los lados hasta aproximadamente la altura de los hombros, juntando los omóplatos de forma natural. Baja las mancuernas lentamente y repite. Mantén el movimiento controlado y evita balancear el cuerpo.',
                    consejos: '• Mantén la espalda recta y el torso estable.\n• Los codos deben estar ligeramente flexionados.\n• Juega con la contracción de los omóplatos.\n• Baja lentamente y controla el movimiento.',
                    errores: '• No balancees el cuerpo.\n• No uses demasiado peso.\n• No bloquees los codos.',
                    musculosPrincipales: ['Deltoides posterior', 'Parte alta de la espalda'],
                    musculosSecundarios: ['Romboides', 'Trapecio medio'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'martes',
                    dificultad: 'facil',
                    material: ['Mancuernas'],
                    intensidadMuscular: { 'Espalda': 80, 'Hombro': 60 }
                },
                {
                    id: 'dumbbell-shrug',
                    nombre: 'Dumbbell Shrug',
                    grupo: 'Trapecio',
                    categoria: 'Aislamiento',
                    urlGif: 'https://gymvisual.com/img/p/1/0/0/7/3/10073.gif',
                    descripcion: 'De pie, con una mancuerna en cada mano y los brazos extendidos a los lados, mantén el cuerpo erguido y eleva los hombros directamente hacia las orejas. Haz una breve pausa en la posición superior y baja lentamente los hombros. No dobles los codos ni hagas círculos con los hombros. El movimiento debe ser vertical y controlado.',
                    consejos: '• Eleva los hombros verticalmente hacia las orejas.\n• Haz una breve pausa en la posición superior.\n• Baja lentamente y controla el movimiento.\n• No dobles los codos.',
                    errores: '• No hagas círculos con los hombros.\n• No uses impulso.\n• No dobles los codos.',
                    musculosPrincipales: ['Trapecio superior'],
                    musculosSecundarios: ['Elevador de la escápula'],
                    series: 3,
                    reps: '10-15',
                    descanso: 45,
                    dia: 'martes',
                    dificultad: 'facil',
                    material: ['Mancuernas'],
                    intensidadMuscular: { 'Trapecio': 90 }
                },
                {
                    id: 'alternating-dumbbell-curl',
                    nombre: 'Alternating Dumbbell Curl',
                    grupo: 'Bíceps',
                    categoria: 'Curl',
                    urlGif: 'https://i.pinimg.com/originals/7d/3c/de/7d3cdeed84c1c19ad372d5b25beffd08.gif',
                    descripcion: 'De pie, sujeta una mancuerna en cada mano con las palmas mirando hacia delante. Flexiona un codo para llevar una mancuerna hacia el hombro mientras mantienes el otro brazo quieto. Baja lentamente y repite con el brazo contrario. Mantén los codos cerca del cuerpo y evita balancear el torso para ayudarte.',
                    consejos: '• Mantén los codos pegados al torso.\n• Controla el movimiento en todo momento.\n• Siente la contracción del bíceps al subir.\n• Baja lentamente y sin impulso.',
                    errores: '• No balancees el cuerpo.\n• No uses demasiado peso.\n• No separes los codos del torso.',
                    musculosPrincipales: ['Bíceps'],
                    musculosSecundarios: ['Braquial'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'martes',
                    dificultad: 'facil',
                    material: ['Mancuernas'],
                    intensidadMuscular: { 'Bíceps': 90 }
                },
                {
                    id: 'hammer-curl',
                    nombre: 'Hammer Curl',
                    grupo: 'Bíceps',
                    categoria: 'Curl',
                    urlGif: 'https://api.smartworkout.app/asset/image/8588e41c-5c2d-4ee0-90ca-ad69b7d0438a',
                    descripcion: 'De pie, sujeta una mancuerna en cada mano con las palmas enfrentadas entre sí. Manteniendo los codos cerca del cuerpo, flexiona los brazos y lleva las mancuernas hacia los hombros sin cambiar el agarre. Baja lentamente y controla todo el recorrido. Evita balancear el cuerpo.',
                    consejos: '• Mantén las palmas enfrentadas (agarre neutro).\n• Los codos deben permanecer cerca del torso.\n• Controla la subida y la bajada.\n• Siente el trabajo del braquial.',
                    errores: '• No balancees el cuerpo.\n• No uses demasiado peso.\n• No separes los codos del torso.',
                    musculosPrincipales: ['Bíceps', 'Braquial'],
                    musculosSecundarios: ['Braquiorradial'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'martes',
                    dificultad: 'facil',
                    material: ['Mancuernas'],
                    intensidadMuscular: { 'Bíceps': 80, 'Antebrazo': 70 }
                },
                {
                    id: 'reverse-dumbbell-curl',
                    nombre: 'Reverse Dumbbell Curl',
                    grupo: 'Antebrazo',
                    categoria: 'Curl',
                    urlGif: 'https://fitnessprogramer.com/wp-content/uploads/2021/04/dumbbell-reverse-curl.gif',
                    descripcion: 'De pie, sujeta una mancuerna en cada mano con las palmas mirando hacia abajo. Mantén los codos cerca del cuerpo y flexiona los brazos para llevar las mancuernas hacia los hombros. Baja lentamente hasta extender los brazos de nuevo. Evita balancear el cuerpo y mantén las muñecas estables.',
                    consejos: '• Mantén las palmas hacia abajo (agarre prono).\n• Los codos deben permanecer cerca del torso.\n• Controla el movimiento y evita el balanceo.\n• Siente el trabajo del antebrazo.',
                    errores: '• No balancees el cuerpo.\n• No uses demasiado peso.\n• No flexiones las muñecas.',
                    musculosPrincipales: ['Braquial', 'Braquiorradial', 'Antebrazo'],
                    musculosSecundarios: ['Bíceps'],
                    series: 3,
                    reps: '10-15',
                    descanso: 45,
                    dia: 'martes',
                    dificultad: 'facil',
                    material: ['Mancuernas'],
                    intensidadMuscular: { 'Bíceps': 70, 'Antebrazo': 85 }
                },

                // JUEVES - NUEVA RUTINA (Tren superior - prioridad brazos)
                {
                    id: 'dumbbell-pullover',
                    nombre: 'Dumbbell Pullover',
                    grupo: 'Pecho / Espalda',
                    categoria: 'Aislamiento',
                    urlGif: 'https://gymvisual.com/img/p/2/8/3/2/8/28328.gif',
                    descripcion: 'Tumbado perpendicular en un banco con la cabeza al borde, sujeta una mancuerna con ambas manos sobre el pecho. Mantén los brazos ligeramente flexionados y lleva la mancuerna de forma controlada por detrás de la cabeza hasta sentir el estiramiento en el pecho y la espalda, y vuelve a la posición inicial sin extender completamente los brazos.',
                    consejos: '• Mantén los brazos ligeramente flexionados durante todo el movimiento.\n• Controla la bajada de la mancuerna.\n• Siente el estiramiento en el pecho y el dorsal.\n• No uses demasiado peso.',
                    errores: '• No bloquees los codos.\n• No bajes la mancuerna demasiado rápido.\n• No arquees la espalda.',
                    musculosPrincipales: ['Pectoral mayor', 'Dorsal ancho'],
                    musculosSecundarios: ['Tríceps', 'Serrato anterior'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'miercoles',
                    dificultad: 'facil',
                    material: ['Banco', 'Mancuerna'],
                    intensidadMuscular: { 'Pecho': 70, 'Espalda': 65, 'Tríceps': 40 }
                },
                {
                    id: 'incline-dumbbell-curl',
                    nombre: 'Incline Dumbbell Curl',
                    grupo: 'Bíceps',
                    categoria: 'Curl',
                    urlGif: 'https://gymvisual.com/img/p/5/0/4/8/5048.gif',
                    descripcion: 'Sentado en un banco inclinado (45°), sujeta una mancuerna en cada mano con los brazos extendidos hacia abajo. Curva las mancuernas hacia los hombros manteniendo los codos fijos y siente la contracción del bíceps. Baja controladamente hasta extender los brazos.',
                    consejos: '• Mantén los codos fijos durante todo el movimiento.\n• Controla la bajada para mantener la tensión.\n• Siente la contracción del bíceps al subir.',
                    errores: '• No muevas los codos.\n• No uses impulso.\n• No bajes demasiado rápido.',
                    musculosPrincipales: ['Bíceps braquial'],
                    musculosSecundarios: ['Braquial'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'jueves',
                    dificultad: 'facil',
                    material: ['Banco inclinado', 'Mancuernas'],
                    intensidadMuscular: { 'Bíceps': 90 }
                },
                {
                    id: 'dumbbell-zottman-curl',
                    nombre: 'Dumbbell Zottman Curl',
                    grupo: 'Bíceps / Antebrazo',
                    categoria: 'Curl',
                    urlGif: 'https://i.pinimg.com/originals/4b/e4/68/4be46841032506b311d43b8d49c6a58a.gif',
                    descripcion: 'De pie, sujeta una mancuerna en cada mano con las palmas mirando hacia delante. Curva las mancuernas hacia los hombros y, en la posición superior, gira las muñecas para que las palmas miren hacia abajo. Baja lentamente las mancuernas con el agarre prono, sintiendo el trabajo del antebrazo.',
                    consejos: '• Gira las muñecas en la posición superior.\n• Controla la bajada con el agarre prono.\n• Mantén los codos estables.',
                    errores: '• No uses demasiado peso.\n• No balancees el cuerpo.\n• No hagas el giro demasiado rápido.',
                    musculosPrincipales: ['Bíceps braquial', 'Braquiorradial'],
                    musculosSecundarios: ['Braquial'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'jueves',
                    dificultad: 'media',
                    material: ['Mancuernas'],
                    intensidadMuscular: { 'Bíceps': 85, 'Antebrazo': 75 }
                },
                {
                    id: 'dumbbell-preacher-curl',
                    nombre: 'Dumbbell Preacher Curl',
                    grupo: 'Bíceps',
                    categoria: 'Curl',
                    urlGif: 'https://gymvisual.com/img/p/1/5/7/7/8/15778.gif',
                    descripcion: 'Coloca un brazo apoyado sobre el respaldo de un banco inclinado (o sobre el propio banco) de forma que el brazo quede extendido y el hombro estable. Sujeta una mancuerna con la mano y curva el brazo hacia el hombro manteniendo el codo fijo. Baja lentamente hasta extender el brazo. Este ejercicio aísla el bíceps y evita el impulso del cuerpo.',
                    consejos: '• Mantén el codo firmemente apoyado.\n• Controla el movimiento sin impulso.\n• Siente la contracción máxima del bíceps.',
                    errores: '• No muevas el codo.\n• No uses demasiado peso.\n• No balancees el cuerpo.',
                    musculosPrincipales: ['Bíceps braquial'],
                    musculosSecundarios: ['Braquial'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'jueves',
                    dificultad: 'facil',
                    material: ['Banco', 'Mancuerna'],
                    intensidadMuscular: { 'Bíceps': 90 }
                },
                {
                    id: 'dumbbell-spider-curl',
                    nombre: 'Dumbbell Spider Curl',
                    grupo: 'Bíceps',
                    categoria: 'Curl',
                    urlGif: 'https://api.smartworkout.app/asset/image/7a6c7c0b-0480-4c45-ba66-18959ec9001f',
                    descripcion: 'Tumbado boca abajo sobre un banco inclinado, deja los brazos colgando hacia el suelo con las mancuernas. Curva las mancuernas hacia los hombros manteniendo los codos fijos y siente la contracción del bíceps al final del recorrido.',
                    consejos: '• Mantén los codos fijos.\n• Controla la subida y la bajada.\n• Aprieta el bíceps en la posición superior.',
                    errores: '• No muevas los codos.\n• No uses demasiado peso.\n• No bajes demasiado rápido.',
                    musculosPrincipales: ['Bíceps braquial'],
                    musculosSecundarios: ['Braquial'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'jueves',
                    dificultad: 'facil',
                    material: ['Banco inclinado', 'Mancuernas'],
                    intensidadMuscular: { 'Bíceps': 90 }
                },
                {
                    id: 'dumbbell-tate-press',
                    nombre: 'Dumbbell Tate Press',
                    grupo: 'Tríceps',
                    categoria: 'Press',
                    urlGif: 'https://gymvisual.com/animated-gifs/1937-dumbbell-tate-press.html',
                    descripcion: 'Tumbado en un banco plano, sujeta una mancuerna en cada mano con las palmas mirando hacia el techo y los codos apuntando hacia afuera. Baja las mancuernas hacia el pecho manteniendo los codos fijos y extiende los brazos para completar el movimiento, sintiendo el tríceps.',
                    consejos: '• Mantén los codos apuntando hacia afuera.\n• Controla la bajada.\n• Siente la contracción del tríceps.',
                    errores: '• No muevas los codos.\n• No uses demasiado peso.\n• No bajes demasiado rápido.',
                    musculosPrincipales: ['Tríceps (cabeza lateral)'],
                    musculosSecundarios: ['Tríceps (cabeza medial)'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'jueves',
                    dificultad: 'media',
                    material: ['Banco', 'Mancuernas'],
                    intensidadMuscular: { 'Tríceps': 85 }
                },
                {
                    id: 'dumbbell-squeeze-press',
                    nombre: 'Dumbbell Squeeze Press',
                    grupo: 'Pecho / Tríceps',
                    categoria: 'Press',
                    urlGif: 'https://gymvisual.com/img/p/1/8/3/5/3/18353.gif',
                    descripcion: 'Tumbado en un banco plano, sujeta las mancuernas juntas con las palmas enfrentadas. Mantén las mancuernas pegadas durante todo el recorrido mientras empujas hacia arriba y bajas controladamente. Este ejercicio enfatiza el trabajo del tríceps y la zona interna del pectoral.',
                    consejos: '• Mantén las mancuernas juntas.\n• Controla el movimiento.\n• Siente la contracción del tríceps y el pecho.',
                    errores: '• No separes las mancuernas.\n• No uses demasiado peso.\n• No bajes demasiado rápido.',
                    musculosPrincipales: ['Tríceps', 'Pectoral mayor (parte interna)'],
                    musculosSecundarios: ['Deltoides anterior'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'miercoles',
                    dificultad: 'media',
                    material: ['Banco', 'Mancuernas'],
                    intensidadMuscular: { 'Tríceps': 80, 'Pecho': 70 }
                },

                // EJERCICIOS DE PIERNAS Y ABDOMEN (conservados para futuro)
                {
                    id: 'sentadilla-goblet',
                    nombre: 'Sentadilla Goblet con mancuerna',
                    grupo: 'Piernas — Gimnasio / Futuro',
                    categoria: 'Sentadilla',
                    urlGif: 'https://fitnessprogramer.com/wp-content/uploads/2023/01/Dumbbell-Goblet-Squat.gif',
                    descripcion: 'Sujeta una mancuerna al pecho, baja como al sentarte manteniendo la espalda recta y el pecho erguido. Baja hasta que los muslos estén paralelos al suelo.',
                    consejos: '• Mantén la espalda recta.\n• Baja hasta que los muslos estén paralelos.\n• Empuja con los talones.',
                    errores: '• No dejes caer las rodillas hacia dentro.\n• No pierdas el equilibrio.',
                    musculosPrincipales: ['Cuádriceps', 'Glúteos', 'Isquiotibiales'],
                    musculosSecundarios: ['Erectores espinales'],
                    series: 4,
                    reps: '8-12',
                    descanso: 90,
                    dia: null,
                    dificultad: 'media',
                    material: ['Mancuerna'],
                    intensidadMuscular: { 'Pierna': 90, 'Glúteos': 75 }
                },
                {
                    id: 'peso-muerto-rumano',
                    nombre: 'Peso muerto rumano',
                    grupo: 'Piernas — Gimnasio / Futuro',
                    categoria: 'Peso muerto',
                    urlGif: 'https://gymvisual.com/img/p/7/6/4/2/7642.gif',
                    descripcion: 'De pie con barra o mancuernas frente a ti, baja con espalda recta hasta sentir el estiramiento de los isquios. Sube impulsando con la cadera.',
                    consejos: '• Mantén la espalda recta.\n• Siente el estiramiento de los isquios.\n• Controla el movimiento.',
                    errores: '• No redondees la espalda.\n• No uses demasiado peso.',
                    musculosPrincipales: ['Isquiotibiales', 'Glúteos', 'Erectores espinales'],
                    musculosSecundarios: ['Cuádriceps'],
                    series: 4,
                    reps: '8-12',
                    descanso: 90,
                    dia: null,
                    dificultad: 'dificil',
                    material: ['Barra', 'Discos'],
                    intensidadMuscular: { 'Pierna': 85, 'Glúteos': 80, 'Espalda': 70 }
                },
                {
                    id: 'zancadas',
                    nombre: 'Zancadas estáticas con mancuernas',
                    grupo: 'Piernas — Gimnasio / Futuro',
                    categoria: 'Zancada',
                    urlGif: 'https://gymvisual.com/img/p/2/3/7/3/9/23739.gif',
                    descripcion: 'Da un paso largo hacia adelante, baja hasta que la rodilla trasera casi toque el suelo, y sube con el talón delantero.',
                    consejos: '• Mantén el torso erguido.\n• Baja controladamente.\n• Empuja con el talón delantero.',
                    errores: '• No pierdas el equilibrio.\n• No bajes demasiado rápido.',
                    musculosPrincipales: ['Cuádriceps', 'Glúteos', 'Isquiotibiales'],
                    musculosSecundarios: ['Gemelos'],
                    series: 4,
                    reps: '8-12',
                    descanso: 60,
                    dia: null,
                    dificultad: 'media',
                    material: ['Mancuernas'],
                    intensidadMuscular: { 'Pierna': 80, 'Glúteos': 75 }
                },
                {
                    id: 'sentadilla-bulgara',
                    nombre: 'Sentadilla búlgara',
                    grupo: 'Piernas — Gimnasio / Futuro',
                    categoria: 'Sentadilla',
                    urlGif: 'https://gymvisual.com/img/p/3/2/8/2/9/32829.gif',
                    descripcion: 'Apoya un pie atrás en un banco, baja hasta que la rodilla delantera forme 90°, y sube con el talón.',
                    consejos: '• Mantén el equilibrio.\n• Baja controladamente.\n• Empuja con el talón delantero.',
                    errores: '• No pierdas el equilibrio.\n• No bajes demasiado rápido.',
                    musculosPrincipales: ['Cuádriceps', 'Glúteos', 'Isquiotibiales'],
                    musculosSecundarios: ['Gemelos'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: null,
                    dificultad: 'dificil',
                    material: ['Banco', 'Mancuernas'],
                    intensidadMuscular: { 'Pierna': 85, 'Glúteos': 80 }
                },
                {
                    id: 'hip-thrust',
                    nombre: 'Hip Thrust',
                    grupo: 'Piernas — Gimnasio / Futuro',
                    categoria: 'Aislamiento',
                    urlGif: 'https://gymvisual.com/img/p/2/0/9/5/6/20956.gif',
                    descripcion: 'Tumbado, apoya la espalda en un banco y sube la cadera con una mancuerna sobre la pelvis.',
                    consejos: '• Aprieta los glúteos en la parte superior.\n• Controla el movimiento.',
                    errores: '• No arquees la espalda.\n• No bajes demasiado rápido.',
                    musculosPrincipales: ['Glúteos'],
                    musculosSecundarios: ['Isquiotibiales'],
                    series: 4,
                    reps: '10-15',
                    descanso: 60,
                    dia: null,
                    dificultad: 'media',
                    material: ['Banco', 'Mancuerna'],
                    intensidadMuscular: { 'Glúteos': 95 }
                },
                {
                    id: 'gemelos',
                    nombre: 'Elevación de gemelos de pie',
                    grupo: 'Piernas — Gimnasio / Futuro',
                    categoria: 'Aislamiento',
                    urlGif: 'https://i.pinimg.com/originals/2f/7c/ca/2f7cca8d37c65384c1d0bd84cc0a91d1.gif',
                    descripcion: 'De pie con mancuernas a los lados, elévate con la punta de los pies y baja controladamente.',
                    consejos: '• Mantén el equilibrio.\n• Controla el movimiento.\n• Siente la contracción de los gemelos.',
                    errores: '• No pierdas el equilibrio.\n• No uses demasiado peso.',
                    musculosPrincipales: ['Gastrocnemio', 'Sóleo'],
                    musculosSecundarios: ['Tibial posterior'],
                    series: 4,
                    reps: '12-20',
                    descanso: 45,
                    dia: null,
                    dificultad: 'facil',
                    material: ['Mancuernas'],
                    intensidadMuscular: { 'Gemelos': 90 }
                },
                {
                    id: 'crunch',
                    nombre: 'Crunch abdominal',
                    grupo: 'Abdomen — Futuro',
                    categoria: 'Aislamiento',
                    urlGif: 'https://i.pinimg.com/originals/34/5c/d9/345cd9414e1e743debd278eaddf33473.gif',
                    descripcion: 'Tumbado boca arriba con rodillas flexionadas, eleva el torso hacia las rodillas contrayendo el abdomen y baja controladamente.',
                    consejos: '• Contrae el abdomen.\n• No tires del cuello.\n• Controla el movimiento.',
                    errores: '• No tires del cuello.\n• No uses impulso.',
                    musculosPrincipales: ['Recto abdominal'],
                    musculosSecundarios: ['Oblicuos'],
                    series: 3,
                    reps: '15-20',
                    descanso: 45,
                    dia: null,
                    dificultad: 'facil',
                    material: ['Colchoneta'],
                    intensidadMuscular: { 'Abdomen': 85 }
                },
                {
                    id: 'elevacion-piernas',
                    nombre: 'Elevación de piernas',
                    grupo: 'Abdomen — Futuro',
                    categoria: 'Aislamiento',
                    urlGif: 'https://gymvisual.com/img/p/5/8/5/9/5859.gif',
                    descripcion: 'Tumbado boca arriba, eleva las piernas rectas hasta formar 90° y baja lentamente manteniendo el abdomen contraído.',
                    consejos: '• Mantén la zona lumbar pegada al suelo.\n• Contra el abdomen.\n• Controla el movimiento.',
                    errores: '• No arquees la zona lumbar.\n• No uses impulso.',
                    musculosPrincipales: ['Recto abdominal inferior'],
                    musculosSecundarios: ['Iliopsoas'],
                    series: 3,
                    reps: '12-15',
                    descanso: 45,
                    dia: null,
                    dificultad: 'media',
                    material: ['Colchoneta'],
                    intensidadMuscular: { 'Abdomen': 80 }
                },
                {
                    id: 'bicicleta-abdominal',
                    nombre: 'Bicicleta abdominal',
                    grupo: 'Abdomen — Futuro',
                    categoria: 'Aislamiento',
                    urlGif: 'https://gymvisual.com/img/p/2/7/6/6/2/27662.gif',
                    descripcion: 'Tumbado, alterna codo con rodilla contraria como si pedalearas.',
                    consejos: '• Mantén el abdomen contraído.\n• Controla el movimiento.\n• No tires del cuello.',
                    errores: '• No tires del cuello.\n• No uses impulso.',
                    musculosPrincipales: ['Recto abdominal', 'Oblicuos externos', 'Oblicuos internos'],
                    musculosSecundarios: ['Transverso abdominal'],
                    series: 3,
                    reps: '15-20',
                    descanso: 45,
                    dia: null,
                    dificultad: 'media',
                    material: ['Colchoneta'],
                    intensidadMuscular: { 'Abdomen': 85, 'Oblicuos': 80 }
                },

                // VIERNES (sin cambios)
                {
                    id: 'press-plano-viernes',
                    nombre: 'Press plano con mancuernas (viernes)',
                    grupo: 'Pecho',
                    categoria: 'Press',
                    urlGif: 'https://gymvisual.com/img/p/1/8/6/4/5/18645.gif',
                    descripcion: 'Tumbado sobre un banco plano, baja las mancuernas de forma controlada hasta el pecho y empuja hacia arriba.',
                    consejos: '• Mantén los pies firmes.\n• Controla la bajada.\n• Exhala al empujar.',
                    errores: '• No bloquees los codos.\n• No bajes demasiado rápido.',
                    musculosPrincipales: ['Pectoral mayor', 'Tríceps', 'Deltoides anterior'],
                    musculosSecundarios: ['Serrato anterior'],
                    series: 4,
                    reps: '8-12',
                    descanso: 90,
                    dia: 'viernes',
                    dificultad: 'media',
                    material: ['Banco', 'Mancuernas'],
                    intensidadMuscular: { 'Pecho': 90, 'Tríceps': 75, 'Hombro': 65 }
                },
                {
                    id: 'remo-una-mano-viernes',
                    nombre: 'Remo a una mano con mancuerna (viernes)',
                    grupo: 'Espalda',
                    categoria: 'Remo',
                    urlGif: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Row.gif',
                    descripcion: 'Apoya rodilla y mano en banco, sube el codo hacia atrás manteniendo la espalda recta.',
                    consejos: '• Mantén la espalda recta.\n• Controla el movimiento.\n• Siente la contracción de la espalda.',
                    errores: '• No redondees la espalda.\n• No uses demasiado peso.',
                    musculosPrincipales: ['Dorsal ancho', 'Romboides', 'Trapecio medio'],
                    musculosSecundarios: ['Bíceps'],
                    series: 4,
                    reps: '8-12',
                    descanso: 90,
                    dia: 'viernes',
                    dificultad: 'media',
                    material: ['Banco', 'Mancuerna'],
                    intensidadMuscular: { 'Espalda': 85, 'Bíceps': 55 }
                },
                {
                    id: 'press-militar-viernes',
                    nombre: 'Press militar sentado (viernes)',
                    grupo: 'Hombro',
                    categoria: 'Press',
                    urlGif: 'https://fitnessprogramer.com/wp-content/uploads/2021/02/Dumbbell-Shoulder-Press.gif',
                    descripcion: 'Sentado, empuja las mancuernas por encima de la cabeza y baja lentamente hasta la altura de los hombros.',
                    consejos: '• Mantén la espalda apoyada.\n• Controla la bajada.\n• Exhala al empujar.',
                    errores: '• No bloquees los codos.\n• No inclines el cuerpo.',
                    musculosPrincipales: ['Deltoides', 'Tríceps', 'Trapecio'],
                    musculosSecundarios: ['Serrato anterior'],
                    series: 4,
                    reps: '8-12',
                    descanso: 90,
                    dia: 'viernes',
                    dificultad: 'media',
                    material: ['Banco', 'Mancuernas'],
                    intensidadMuscular: { 'Hombro': 90, 'Tríceps': 70, 'Trapecio': 60 }
                },
                {
                    id: 'remo-banco-inclinado-viernes',
                    nombre: 'Remo en banco inclinado con mancuernas (viernes)',
                    grupo: 'Espalda',
                    categoria: 'Remo',
                    urlGif: 'https://gymvisual.com/img/p/1/4/9/7/3/14973.gif',
                    descripcion: 'Tumbado boca abajo en banco inclinado, tira las mancuernas hacia arriba manteniendo la espalda recta.',
                    consejos: '• Mantén la espalda recta.\n• Controla el movimiento.\n• Siente la contracción de la espalda.',
                    errores: '• No uses demasiado peso.\n• No pierdas el control.',
                    musculosPrincipales: ['Dorsal ancho', 'Romboides', 'Trapecio medio'],
                    musculosSecundarios: ['Deltoides posterior'],
                    series: 4,
                    reps: '8-12',
                    descanso: 90,
                    dia: 'martes',
                    dificultad: 'media',
                    material: ['Banco inclinado', 'Mancuernas'],
                    intensidadMuscular: { 'Espalda': 80, 'Bíceps': 50 }
                },
                {
                    id: 'aperturas-viernes',
                    nombre: 'Aperturas con mancuernas (viernes)',
                    grupo: 'Pecho',
                    categoria: 'Apertura',
                    urlGif: 'https://gymvisual.com/img/p/1/0/2/8/0/10280.gif',
                    descripcion: 'Abre los brazos manteniendo una ligera flexión de los codos hasta notar el estiramiento del pecho y vuelve lentamente.',
                    consejos: '• Mantén los codos ligeramente flexionados.\n• Siente el estiramiento.\n• Controla el movimiento.',
                    errores: '• No bloquees los codos.\n• No uses demasiado peso.',
                    musculosPrincipales: ['Pectoral mayor', 'Deltoides anterior'],
                    musculosSecundarios: ['Bíceps'],
                    series: 4,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'jueves',
                    dificultad: 'facil',
                    material: ['Banco', 'Mancuernas'],
                    intensidadMuscular: { 'Pecho': 80, 'Hombro': 50 }
                },
                {
                    id: 'elevaciones-laterales-viernes',
                    nombre: 'Elevaciones laterales (viernes)',
                    grupo: 'Hombro',
                    categoria: 'Aislamiento',
                    urlGif: 'https://gymvisual.com/img/p/5/1/3/7/5137.gif',
                    descripcion: 'Eleva las mancuernas lateralmente hasta la altura de los hombros manteniendo una ligera flexión en los codos.',
                    consejos: '• Mantén los codos ligeramente flexionados.\n• Controla el movimiento.',
                    errores: '• No balancees el cuerpo.\n• No uses demasiado peso.',
                    musculosPrincipales: ['Deltoides medio', 'Supraespinoso'],
                    musculosSecundarios: ['Trapecio'],
                    series: 4,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'viernes',
                    dificultad: 'facil',
                    material: ['Mancuernas'],
                    intensidadMuscular: { 'Hombro': 85 }
                },
                {
                    id: 'curl-martillo-viernes',
                    nombre: 'Curl martillo (viernes)',
                    grupo: 'Bíceps',
                    categoria: 'Curl',
                    urlGif: 'https://api.smartworkout.app/asset/image/8588e41c-5c2d-4ee0-90ca-ad69b7d0438a',
                    descripcion: 'Agarre neutro, muñeca recta todo el movimiento. Curva la mancuerna hacia el hombro.',
                    consejos: '• Mantén los codos pegados al torso.\n• Controla el movimiento.',
                    errores: '• No uses demasiado peso.\n• No balancees el cuerpo.',
                    musculosPrincipales: ['Braquial', 'Braquiorradial'],
                    musculosSecundarios: ['Bíceps braquial'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'jueves',
                    dificultad: 'facil',
                    material: ['Mancuernas'],
                    intensidadMuscular: { 'Bíceps': 80, 'Antebrazo': 70 }
                },
                {
                    id: 'extension-triceps-cabeza-viernes',
                    nombre: 'Extensión de tríceps por encima de la cabeza (viernes)',
                    grupo: 'Tríceps',
                    categoria: 'Aislamiento',
                    urlGif: 'https://media.tenor.com/V3J-mg9gH0kAAAAM/seated-dumbbell-triceps-extension.gif',
                    descripcion: 'Sentado, sujeta una mancuerna con ambas manos por encima de la cabeza y extiende completamente los brazos.',
                    consejos: '• Mantén los codos cerca de la cabeza.\n• Controla el movimiento.',
                    errores: '• No separes los codos.\n• No bajes demasiado rápido.',
                    musculosPrincipales: ['Tríceps (cabeza larga)'],
                    musculosSecundarios: ['Tríceps (cabeza lateral)', 'Tríceps (cabeza medial)'],
                    series: 3,
                    reps: '10-15',
                    descanso: 60,
                    dia: 'jueves',
                    dificultad: 'facil',
                    material: ['Mancuerna'],
                    intensidadMuscular: { 'Tríceps': 90 }
                }
            ];
            return exerciseDatabase;
        }

